# Generated by Django 2.2 on 2021-09-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210929_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
